Development for 0.0.10.

diff --git a/scripts/runapp-g3wfpipe b/scripts/runapp-g3wfpipe
--- a/scripts/runapp-g3wfpipe
+++ b/scripts/runapp-g3wfpipe
@@ -156,14 +156,18 @@ if [ -n "$CJOB" ]; then
     echo "ERROR: Unable to find name of run directory for continuation job $CJOB"
     exit 1
   fi
-  for DIR in $PDIR $PDIR/submit; do
+  for DIR in $PDIR $PDIR/submit $DIR/runinfo; do
     if [ ! -r $DIR ]; then
       echo "ERROR: Unable to find continuation run directory $DIR"
       exit 1
     fi
   done
   if ! ln -s $PDIR/submit .; then
-    echo "ERROR: Unable to link $PDIR/submit ti $(pwd)"
+    echo "ERROR: Unable to link $PDIR/submit to $(pwd)"
+    exit 1
+  fi
+  if ! ln -s $PDIR/runinfo .; then
+    echo "ERROR: Unable to link $PDIR/runinfo to $(pwd)"
     exit 1
   fi
 fi
